#!/bin/bash

curl -X POST -u testuser:testpass "https://localhost:8090/createUser" 
sleep 5
token=$(curl -u testuser:testpass "https://localhost:8090/getToken")
sleep 5
curl -H "Authorization: Bearer $token" "https://localhost:8090/api/status"