#!/bin/bash

export GRPC_GO_LOG_VERBOSITY_LEVEL=99
export GRPC_GO_LOG_SEVERITY_LEVEL=info

buf beta mod update
buf generate

echo "Services and messages generated, contents:"
ls -l proto/service

go mod tidy

killall CS467_SU21
go run . :8080 :8090 &

sleep 5