#!/bin/bash

export GRPC_GO_LOG_VERBOSITY_LEVEL=99
export GRPC_GO_LOG_SEVERITY_LEVEL=info

buf beta mod update
buf generate

echo "Services and messages generated:\n"
ls -l proto/service

go env
go run . :8080 :8090 &

sleep 10