name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-run-bdd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.5

      - name: Generate certificates for next step
        uses: kofemann/action-create-certificate@v0.0.4
        with:
          hostcert: 'example.crt'
          hostkey:  'example.key'
          cachain:  'ca-chain.pem'

      - name: Use generated certificates
        run: |
            openssl x509 -in example.crt -noout -text

      - name: Run install script
        run: |
          ./install
      - name: Run service
        run: |
          ./startService
      - name: Run BDDs
        run: |
          ./bddScript
        env:
          SCM_APP_SECRET: ${{secrets.GITHUB_TOKEN}}

