name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-run-bdd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.5

      - name: Run install script
        run: |
          ./install
      - name: Run service
        run: |
          ./startService
      - name: Run BDDs
        run: |
          curl -u test:placeholder "localhost:8090/api/status"
          sleep 5

